### ISSUE TITLE
this example doesn't work with schematics 8

### ISSUE THREAD

**Issue by JcOnSoftware** [oktadeveloper/okta-angular-schematics-example#1]
**Affected Package**
The issue is caused by package "@schematics/angular": "^8.2.0"

**Is this a regression?**
This was working in version 7.2

**Description**
When I updated the schematics with angular 8 and schematics 8.2.0, I'm getting a error to run unit tests for this example.

🔬 **Minimal Reproduction**
Just update package.json to angular@8.2.0

🌍 **Your Environment**
Angular Version:

"dependencies": {
    "@angular-devkit/core": "^8.2.0",
    "@angular-devkit/schematics": "^8.2.0",
    "@types/jasmine": "^3.3.9",
    "@types/node": "^8.0.31",
    "jasmine": "^3.3.1",
    "typescript": "~3.5.3"
  },
  "devDependencies": {
    "@schematics/angular": "^8.2.0"
  }

![image](https://user-images.githubusercontent.com/333062/62385745-7d279000-b51b-11e9-897e-897ed4d061a3.png)

**Comment by mraible** [comment]
You need to update @oktadev/schematics to [v0.8.0](https://github.com/oktadeveloper/schematics/releases/tag/v0.8.0), or just create a new Angular 8 project and run `ng add @oktadev/schematics`.

**Comment by JcOnSoftware** [comment]
Thanks!
